name: "Atess Inverter"
version: "0.4.1"
slug: "atess"
description: "Atess Inverter"
init: false
startup: application
boot: auto
url: "https://github.com/Voyanti/ha-atess"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  servers:
    - name: "A1"
      serialnum: "A2340700442"
      server_type: "ATESS_INVERTER"
      connected_client: "Client1"
      modbus_id: 1
  clients:
    - name: "Client1"
      type: "TCP"
      host: "10.0.0.15"
      port: 502
  pause_interval_seconds: 0.5
  sleep_over_midnight: true
  sleep_midnight_minutes: 10
  mqtt_host: "localhost"
  mqtt_port: 1884
  # mqtt_host: "core-mosquitto"
  # mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mwtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "modbus"
schema:
  servers:
    - name: str
      serialnum: str
      server_type: list(ATESS_INVERTER)
      connected_client: str
      modbus_id: int(0,255)
      # PT: int?
      # CT: int?
  clients:
    - name: str
      type: list(TCP|RTU)
      host: str?
      port: str?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  pause_interval_seconds: int
  sleep_over_midnight: bool
  sleep_midnight_minutes: int
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str
