name: "Sungrow Inverter Addon"
version: "0.2.3"
slug: "sungrow"
description: "Sungrow Inverter Addon"
init: false
startup: application
boot: auto
url: "https://github.com/heinrich321/voyanti-sungrow/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt:
    host: "core-mosquitto"
    port: 1883
    user: "mqtt"
    password: "mqtt"
    ha_discovery: true
    ha_discovery_topic: "homeassistant"
    base_topic: "modbus"
  clients:
    - name: "ModebusTCP"
      nickname: "Client1"
      type: "TCP"
      connection_specs: "Sungrow_Logger"
  servers:
    - name: "SunGrow Inverter 1"
      nickname: "SG1"
      serialnum: "12345678"
      server_type: "SunGrow Logger"
      connected_client: "Client1"
      device_addr: 1
  connection_specs:
    - name: "Sungrow_Logger"
      connection_method: "TCP"
      host: "10.0.0.x"
      port: 502
