name: "Sungrow Inverter Addon"
version: "0.1.0"
slug: "sungrow_inverter"
description: ""
init: false
startup: application    # check
boot: auto

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  clients:
    - name: "usb_to_modbus"
      nickname: "Client1"
      connection_specs: "SunGrow Inverter"      # selects 8N1 and 9600 baud
      port: "dev/tty1"
  servers: 
    - name: "SunGrow Inverter 1"
      nickname: "SG1"
      serialnum: "12345678"
      server_type: "SunGrow Inverter"
      connected_client: "Client1"
      # read all registers for now. invalid registers are Uint/Int_Max
  connection_specs:
    SunGrow Inverter:
      connection_method: "RTU"
      baudrate: 9600
      bytesize: 8
      parity: false
      stopbits: 1


