name: "Sungrow Inverter Addon"
version: "0.3.29"
slug: "sungrow"
description: "Sungrow Inverter Addon"
init: false
startup: application
boot: auto
url: "https://github.com/heinrich321/voyanti-sungrow/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt:
    host: "core-mosquitto"
    port: 1883
    user: "mqtt"
    password: "mqtt"
    ha_discovery: true
    ha_discovery_topic: "homeassistant"
    base_topic: "modbus"
  clients:
    - name: "ModebusTCP"
      nickname: "Client1"
      type: "TCP"
      connection_specs: "Sungrow_Logger"
  servers:
    - name: "Sungrow Inverter 1"
      nickname: "SG1"
      serialnum: "A2340700442"
      server_type: "SUNGROW_INVERTER"
      connected_client: "Client1"
      device_addr: 1
    - name: "Sungrow Logger 1"
      nickname: "SGL1"
      serialnum: "B2391405111"
      server_type: "SUNGROW_LOGGER"
      connected_client: "Client1"
      device_addr: 247
    - name: "Grid Meter"
      nickname: "GM"
      serialnum: "unknown"
      server_type: "ACREL_METER"
      connected_client: "Client1"
      device_addr: 2
  connection_specs:
    - name: "Sungrow_Logger"
      connection_method: "TCP"
      host: "10.0.0.15"
      port: 502
schema:
    mqtt:
      host: str
      port: int
      user: str
      password: str
      ha_discovery: bool
      ha_discovery_topic: str
      base_topic: str
    clients:
      - name: str
        nickname: str
        type: str
        connection_specs: str
    servers:
      - name: str
        nickname: str
        serialnum: str
        server_type: str
        connected_client: str
        device_addr: int(0,255)
    connection_specs:
      - name: str
        connection_method: str
        host: str
        port: int