name: "Sungrow Inverter Addon"
version: "0.1.0"
slug: "sungrow_inverter"
description: ""
init: false
startup: application    # check
boot: auto

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  clients:
    - name: "usb_to_modbus"
      nickname: "Client1"
      connectionspecs: "SunGrow Inverter"      # selects 8N1 and 9600 baud
  servers: 
    - name: "SunGrow Inverter 1"
      serialnum: "12345678"
      nickname: "SG1"
      server_type: "SunGrow Inverter"
      # read all registers for now. invalid registers are Uint/Int_Max

