name: Build and Push to GHCR

on:
  push:
    branches:
      - main  # Change this if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract version from config.yaml
        id: get_version
        run: |
          # Install yq to parse YAML
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          # Extract version from config.yaml
          VERSION=$(yq eval '.version' config.yaml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for Raspberry Pi 5
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64  # Target architecture for Raspberry Pi 5
          tags: ghcr.io/${{ env.REPO_OWNER }}/${{ github.event.repository.name }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
